### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by jamonholmgren** [Serg-Norseman/NorseWorld-Ragnarok#2]
Hey there! I'm happy to see this remake of one of my favorite games.

Where can I download an executable of this game? I don't mind compiling from source, too, if you give me instructions.

Thanks!

**Comment by Serg-Norseman** [comment]
[Releases](https://github.com/Serg-Norseman/NorseWorld-Ragnarok/releases) section.

This remake was about 80-90% complete. Then he stopped in development, due to the lack of a team (it was boring to continue alone). Glad you like this game :) it's rare

**Comment by jamonholmgren** [comment]
Oh, duh -- I should have looked at releases.

Yeah, I just finished the original game in DosBox (although I didn't win, because I only completed two of the quests). I'm going to try again and try to win the final battle soon.

Thanks!
